services:
  backend:
    build: 
      context: ./virtualguessr_back
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./virtualguessr_back/data:/virtualguessr_back/data
  frontend:
    build:
      context: ./virtualguessr_front
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/build
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend_build:/usr/share/nginx/html
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  frontend_build: