version: '3.8'

services:
  web:
    build: 
      context: ./virtualguessr_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./virtualguessr_back/data:/virtualguessr_back/data
    # command: uvicorn main:app --host 0.0.0.0 --reload